export const babyLonToBhagdadTripAccData = [
    {
        day: 1,
        description: "<strong>ARRIVE IN BASRA, IRAQ (D)</strong>",
        activities: [
            "Welcome to Iraq! Upon your arrival in Basra, you'll get your visa at immigration and smoothly proceed through customs.After collecting your luggage, you'll meet your friendly driver who will transfer you to your hotel. Basra, nestled on the banks of the Shatt Al - Arab where the Tigris and Euphrates rivers converge, has held strategic importance since ancient times.This historic city, once visited by Alexander the Great, is steeped in over a thousand years of oral and literary traditions.It is famed as the legendary home of Sinbad the Sailor, the intrepid hero of One Thousand and One Arabian Nights.In the twentieth century, British colonial efforts transformed Basra into a modern port, earning it the nickname 'Venice of the East' for its picturesque canals.However, Basra's charm has been scarred by modern conflicts.The city endured significant damage during the Iran- Iraq War and has yet to fully recover from the devastation of the First and Second Gulf Wars.Visitors often witness a city caught in a relentless cycle of construction and destruction, devastation and resurgence. Upon your arrival at the hotel, your guide will be waiting to assist you.After checking in and taking some time to relax, you'll have a brief orientation followed by a delightful dinner at your hotel."
        ]
    },
    // Day 2
    {
        day: 2,
        description: "<strong>BASRA EXPLORATIONS (B, L, D)</strong>",
        activities: [
            "After a hearty breakfast, step into the enchanting streets of Old Basra. Stroll along the serene canals, flanked by the magnificent shenashil—these historic Ottoman - style villas boast intricate brickwork and their signature balconies. Though many of these once - grand homes now lie in decay, mere shadows of Basra’s illustrious past, around 150 shenashil still stand.European Union funding is set to restore a select few, preserving a fraction of their former glory. One of these preserved treasures, a nineteenth - century mansion once owned by a prosperous Greek merchant, awaits your visit. Next, continue your journey to the Armenian Church.Originally constructed in 1763, much of its current form reflects later periods of reconstruction and restoration.From this historical landmark, you’ll travel to the Imam Ali Mosque, a significant site as Basra’s first mosque and one of the oldest in the Islamic world.Despite a devastating fire that claimed much of the original structure, the mosque’s minaret proudly dates back to 635 CE. For lunch, indulge in the flavors of southern Iraq at a local restaurant.Savor a variety of rice dishes, alongside the ever- popular beef and chicken kebabs.Afterward, embark on a tranquil boat ride along the Shatt Al - Arab.This vital waterway, formed by the confluence of the Tigris and Euphrates rivers, played a crucial role in the Silk Road's mercantile era and remains pivotal today, with a significant portion of the world’s oil passing through its channels. As the day winds down, enjoy an authentic Iraqi - style barbecue dinner before heading back to your hotel, carrying with you the rich experiences of Basra's historic and cultural tapestry."
        ]
    },
    // Day 3
    {
        day: 3,
        description: "<strong>THE MARSHLANDS (B, L, D)</strong>",
        activities: [
            `This morning, you set out on an unforgettable journey to the ancient Mesopotamian town of Al-Qurnah. After an hour’s drive, you arrive at the legendary confluence of the Tigris and Euphrates rivers, known locally as the Dijla and Al-Furat. Here, in a modest park, stands a venerable tree, carefully shielded by protective walls. This is the shrine of the Cidra el Muntaha, the Tree of Knowledge, believed to be the very tree whose forbidden fruit led to Adam and Eve’s expulsion from the Garden of Eden. Continuing your adventure, you drive onward to the mesmerizing Mesopotamian Marshes, passing through several checkpoints (keep your passport ready).You step off the bus near a remarkable mudhif, a traditional reed house that typifies this wetland region.These structures, crafted by ancient Sumerians as early as 4500 BCE, are immortalized in The Epic of Gilgamesh.Take a moment to admire the intricate woven architecture as you sit on the carpeted floor, savoring tea or coffee. After your refreshment, you board a traditional motorboat to glide through this miraculous aquatic landscape, a sanctuary for egrets, kingfishers, and herons.This is also the homeland of the Marsh Arabs, or Ma'dan, descendants of the Sumerians who have thrived here for 5,000 years, creating a unique lifestyle, architecture, and culture. In the 1990s, Saddam Hussein ordered the drainage of these marshes, aiming to transport military equipment and punish the Marsh Arabs for their opposition. This act was decried worldwide as a humanitarian and ecological catastrophe. Today, the marshes are undergoing a hopeful restoration, and some displaced families have returned.Disembark to walk along a road constructed during Saddam’s regime, then return by boat to the mudhif for a delightful lunch with a local family. This afternoon, you drive to Nasiriyah, traversing a landscape scarred by decades of conflict and neglect, a legacy of Iraqi, American, and British interventions.Once renowned for its bountiful date farms, this region now bears a starkly different face; the lush valleys that once teemed with agriculture now yield millions of barrels of oil instead.Upon arrival in Nasiriyah, check into your hotel and, if time permits, explore the bustling souk.As the provincial capital, Nasiriyah’s souk is a vibrant hub, teeming with men, women, and children navigating on foot and scooters, hawking their wares in lively stalls.This is a place where the pulse of everyday life beats strong, offering a rich tapestry of sights, sounds, and scents that will linger in your memory.`
        ]
    },
    // Day 4
    {
        day: 4,
        description: "<strong>THE ANCIENT CITIES (B, L, D)</strong>",
        activities: [
            "This morning, you embark on a journey to the awe-inspiring ziggurat of Ur, a marvel of the ancient world often dubbed 'Iraq’s answer to the pyramids.' Despite being inhabited since prehistoric times, Ur truly flourished as a city - state in the 27th century BCE.Its decline came about due to a confluence of political upheavals, prolonged droughts, and the changing course of the Euphrates River, compounded by the rise of the Achaemenid Empire.By the early 5th century BCE, the city was likely abandoned.It lay in silence for nearly 1300 years until Victorian- era British archaeologists began their excavations.As you approach the impressive ziggurat, you can't help but marvel at its enduring grandeur, which stands as a testament to a bygone era.This monumental structure, one of the few remnants visible today(only 5 % of the site has been excavated), was dedicated to the moon god Nanna.Its architectural elements echo the biblical descriptions of the Tower of Babel, hinting at the city's historical and cultural significance.In the afternoon, your journey takes you to the site of Tello, known in antiquity as Girsu.Here, the eroded ruins may not be the main attraction; instead, it's the treasure trove of artifacts that captivates visitors. Among the most significant discoveries are 2,000 tablets from the archives dedicated to the goddess Ba’U.As you wander among the scattered shards of pottery and ancient tablets, your guide regales you with tales of these mysterious artifacts, whose secrets were unlocked only recently.The current excavations are a collaborative effort between British and Iraqi archaeologists, shedding new light on this ancient civilization. After a day of exploring these ancient wonders, you return to Nasiriyah, where a delightful dinner awaits you at your hotel.The day's experiences linger in your mind as you reflect on the rich history and cultural legacy of this remarkable region."
        ]
    },
    // Day 5
    {
        day: 5,
        description: "<strong>DRIVE TO NAJAF (B, L, D)</strong>",
        activities: [
            "Departing from Nasiriyah this morning, your journey takes you to Najaf, with an enriching stop in Uruk, often hailed as the world’s first city.Inhabited since 4000 BCE, Uruk is renowned as the birthplace of the earliest known forms of human writing.This ancient city is steeped in history, closely tied to the epic poem of Gilgamesh, who is believed to have been the king of this illustrious Sumerian city - state.As you explore the ruins, you’ll encounter a magnificent ziggurat, alongside the remnants of temples and palaces.Some of their bricks still shimmer with a transcendent blue glaze.Wandering among the fragments of ancient pottery shards and shells, you are reminded of a time when the Euphrates flowed nearby, occasionally flooding the area with seawater. Your journey continues to Najaf, one of Iraq’s holiest cities and a pivotal hub of Shi’ite political power.Every year, millions of pilgrims travel to pay their respects at the mausoleum and shrine of Imam Ali, the cousin and son-in -law of Prophet Mohammed.As the fourth caliph and the spiritual founder of the Shi’ite sect, Ali’s martyrdom in 661 AD marked a significant division in the Islamic world. In Najaf, you visit the historic complex of the Great Mosque of Kufa.Dating back to 670 CE, it is one of the oldest mosques in the world and holds profound significance as the place where Ali was fatally wounded while praying. Tradition also claims this sacred site to be where Noah began constructing the Biblical Ark. After an inspiring day immersed in history and spirituality, you continue to your hotel, where you check in and unwind before dinner."
        ]
    },
    // Day 6
    {
        day: 6,
        description: "<strong>EXPLORING NAJAF (B, L, D)</strong>",
        activities: [
            "Depart from Najaf to the historic town of Al-Kifl, where you can glimpse the ancient tomb of the 6th-century BCE prophet Ezekiel.Though entry into the tomb itself is not permitted, the exterior offers a fascinating sight.The tomb holds a unique place of reverence in both Islam and Judaism, serving as both a mosque and a synagogue.Its decor is a harmonious blend of Hebrew script and Islamic artistry, showcasing a rare cultural confluence. Upon returning to Najaf, you'll visit the world-renowned Wadi Al-Salaam Cemetery, the largest cemetery on the planet. This final resting place for eight million souls sprawls over nearly 2, 300 acres, encompassing approximately 13% of the city.The sheer expanse and historical significance of this cemetery are profoundly moving. Next, you will experience the majestic mausoleum of Imam Ali, a site that inspires both joyous excitement and deep devotion.The shrine's magnificent golden dome stands tall over an intricate complex of courtyards, halls, and the mausoleum itself.As you walk through richly decorated mosaic tiles, intricate inlaid calligraphy, and grand mirrored hallways, you join hundreds, if not thousands, of devotees and pilgrims in their prayers, reflections, and moments of rest. After wandering through the vibrant nearby souk, filled with the sounds and scents of local life, you will return to your hotel for a well- deserved dinner."
        ]
    },
    // Day 7
    {
        day: 7,
        description: "<strong>DRIVE TO KARBALA VIA UKHAIDER (B, L, D)</strong>",
        activities: [
            "Today, you embark on a captivating journey from Najaf to Karbala. On your way, you will stop to explore the magnificent al - Ukhaider Palace, a fortress and residential complex shrouded in mystery.Believed to have been constructed in 775 CE by the nephew of an Abbasid caliph, the palace showcases a fascinating blend of Byzantine and Islamic architectural styles that once mesmerized the famed 19th - century British traveler, Gertrude Bell. Upon arriving in Karbala, you will delight in a sumptuous lunch at a charming local restaurant.Like Najaf, Karbala is a revered holy city, home to the sacred shrine of Imam Hussein ibn Ali, the grandson of the Prophet Mohammed, and hi half - brother Abbas.The tragic deaths of Imam Hussein and Abbas in the Battle of Karbala in 680 CE, a fierce conflict among Muslims over the rightful successor of the caliphate, remain deeply ingrained in Shi'ite identity and memory. After lunch, you will continue your pilgrimage to the interconnected shrines of Imam Hussein and Abbas.These sacred sites said to be built on the very battleground where the historic battle unfolded, are adorned with majestic golden minarets, resplendent domes, and intricate glazed tiles.Here, you will have the extraordinary opportunity to immerse yourself in the fervent worship, profound sorrow, and jubilant devotion of hundreds of pilgrims, sharing in an unforgettable spiritual experience."
        ]
    },
    // Day 8
    {
        day: 8,
        description: "<strong>BABYLON AND BAGHDAD (B, L, D)</strong>",
        activities: [
            "After breakfast, embark on a journey to the historic city of Babylon, the illustrious capital of the ancient Babylonian Empire.Known for the pioneering legal reforms of King Hammurabi in the 18th century BCE, Babylon's most splendid era was under the visionary reign of Nebuchadnezzar II in the sixth century BCE.A visit to this remarkable site weaves together ancient history and the modern narrative of Iraq.In a nod to Nebuchadnezzar II, Saddam Hussein poured vast resources into reconstructing Babylon, embedding his own name on newly fired bricks as a testament to his restoration efforts.The reconstructed Palace of Nebuchadnezzar II showcases bricks inscribed with the names of both rulers. Adjacent to this ancient palace lies the famous Processional Way, culminating at the foundations of the legendary Ishtar Gate.The gate’s foundations are adorned with impressions of bulls and mythical chimeras—creatures with features of lions, snakes, and eagles.The original, magnificent blue- tiled gate was dismantled post - World War I by German archaeologists and now resides in Berlin's Pergamon Museum. Dominating the skyline of Babylon is a more recent structure: the former palace of Saddam Hussein.This haunting complex, now a derelict shell of broken windows, stripped fixtures, and graffiti, was looted by American troops and later by locals.Despite the uncertainty of whether Saddam ever visited this palace, it's rumored that he insisted his staff prepare three meals daily just in case he decided to stop by. Conclude your visit by traveling to Baghdad, where you’ll check into your hotel before enjoying a delightful dinner."]
    },
    // Day 9
    {
        day: 9,
        description: "<strong>BAGHDAD (B, L, D)</strong>",
        activities: [
            "Welcome to Baghdad, a city that has stood at the heart of the Islamic world since the 8th century BCE. Once a bustling metropolis of the Ottoman Empire, a strategic base during British colonial rule, and now the vibrant capital of modern Iraq, Baghdad has experienced cycles of prosperity, destruction, and renewal.Visitors are often captivated by the residents' unwavering energy, ambition, and resilience. Your morning begins with a visit to the Iraq Museum, home to a stunning array of treasures from Sumer, Assyria, ancient Persia, and various Islamic traditions.The museum, which suffered significant looting in 2003 during the American invasion with an estimated 15,000 artifacts stolen, has made an impressive recovery.Many artifacts have been returned, though some, like the ancient Golden Lyre of Ur, sustained damage.The lyre was infamously discovered in the museum's parking lot, missing its golden bull’s head, which was later recovered at the National Bank of Iraq. Since reopening to the public in 2015, the Iraq Museum has reclaimed its status as one of the world's premier collections of antiquities. After an enlightening museum tour, your guide and driver take you to the former Jewish Quarter.Here, you can unwind with a cup of tea, coffee, or a taste of shisha.Jewish culture thrived in this region for millennia, with Jewish communities contributing richly to Baghdadi life well into the nineteenth century.The twentieth century brought increased antisemitism and violence, prompting many Iraqi Jewish families to emigrate to Europe or Israel.Today, only one synagogue remains in Baghdad, a testament to the city's once-vibrant Jewish heritage. Next, stretch your legs on a walking tour through Old Baghdad.Stroll down the famous Al- Mutanabbi Street, named after a 10th - century Iraqi poet and historically the intellectual hub of the city.In 2007, a car bomb tragically destroyed its iconic open - air book market, claiming more than 30 lives.However, the spirit of Al - Mutanabbi Street endured, with artists, poets, and writers creating tributes to its literary culture.The street has since been restored, inviting visitors to once again explore its rich array of books and enjoy its unique atmosphere."
        ]
    },
    // Day 10
    {
        day: 10,
        description: "<strong>CTESIPHON & BAGHDAD (B, L, D)</strong>",
        activities: [
            "This morning, embark on a journey approximately 20 miles southeast of Baghdad to explore the ancient ruins of Ctesiphon.Founded around 128 BCE, Ctesiphon served as the winter capital for both the Parthian and Sasanian Empires.Following the Muslim conquest of Persia in 651 CE, the city gradually fell into disrepair.Today, its most iconic remnant is the Taq Kasra, a majestic vaulted hall that once formed part of a royal palace.The arch of Taq Kasra is renowned as one of the largest single- span vaults of unreinforced brickwork in the world.Although parts of Ctesiphon are currently inaccessible due to ongoing archaeological renovations, the surrounding fields remain a popular recreation spot for families, and the lush grasslands provide excellent forage for flocks of goats under the watchful eyes of shepherds. After returning to Baghdad, take a leisurely break for tea before heading to the Al - Mustansiriya Madrassah, one of the oldest Islamic institutions of higher learning in the world.Established in 1227 by Abbasid Caliph al - Mustansir and completed in 1234, the madrassah was a marvel of its time.Though the Mongols sacked Baghdad in 1258, they left the building intact but tragically killed the students and threw thousands of books into the Tigris River, which, as legend has it, turned black from the ink.Today, the madrassah is part of Al - Mustansiriya University and continues to be a vibrant center of learning. Your journey continues to the imposing Martyr’s Monument, commissioned by Saddam Hussein in 1981 as a memorial to the Iraqis who perished during the Iran - Iraq War.Over time, it has evolved into a tribute to all Iraqis who have died for their country, including those who suffered under Hussein's regime. The monument's two massive blue half - domes, symbolizing life and death, create a striking visual impact.A twisted metal flagpole emerges from the underground museum between the domes, and a fountain symbolizes the blood of the fallen, adding to the monument's profound emotional resonance."
        ]
    },
    // Day 11
    {
        day: 11,
        description: "<strong>BAGHDAD AND THE GREAT MOSQUE OF SAMARRA (B, L, D) </strong>",
        activities: [
            "Begin your day at the iconic Al Tahrir (Liberation) Square. In October 2019, this vibrant heart of Baghdad saw youth activists gather to protest their dire economic conditions.Today, many of these activists remain imprisoned, and their families often return to the square to peacefully protest beneath the Freedom Monument—a striking mural commemorating the 1958 establishment of the Republic of Iraq.Nearby, colorful protest murals adorn the underpass and surrounding buildings, adding a vivid backdrop to the area. Next, embark on a two- hour drive to the historic city of Samarra to visit its renowned mosque and tower.The Great Mosque, also known as the Malwiyya Mosque, was completed in 851 CE and was one of the largest mosques of its time. Though the mosque was destroyed in 1278 by Hulagu Khan, the grandson of Genghis Khan, its outer wall and unique minaret still stand.The Malwiyya minaret, a spiraling tower that rises over 150 feet into the sky, is considered and architectural marvel.The minaret is encircled by a spiraling ramp, offering a challenging but rewarding climb, though it lacks railings, making it an adventure for the brave - hearted. Conclude your day with a delightful dinner back at your hotel in Baghdad, reflecting on the rich history and resilient spirit of Iraq."
        ]
    },
    // Day 12
    {
        day: 12,
        description: "<strong>DEPARTURE (B)</strong>",
        activities: [
            "This morning, you'll be escorted to the airport for your journey back home. Our MidAsia Routes services conclude here. Safe travels and we hope to see you again soon!"
        ]
    }
];
