name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js, npm and dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change to your desired Node.js version

    - run: npm install

    - name: Build the project
      run: npm run build  # Change to your build script if different

    - name: Deploy to Hostinger
      uses: appleboy/scp-action@master
      with:
        host: 62.72.56.213  # Replace with your actual Hostinger IP address or domain
        username: srv655107.hstgr.cloud  # Replace with your Hostinger username
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        target: /root/Travelroutes/build  # Change to your deployment directory
        source: build/  # Adjust the source to match your build output directory
